#!/bin/bash

IMAGE_NAME=rif-notifier-image

echo "You sure you want to generate the image? [y/N]"
read SURE

if [ "${SURE}" != "y" ]; then
    exit 0
fi

echo "Clean cache? [y/N]"
read CLEAN_CACHE

if [ "${CLEAN_CACHE}" == "y" ]; then
    echo "Cleaning Cache and Generating Image"
    sudo docker build --no-cache -t ${IMAGE_NAME} .
else
    echo "Generating Image"
    sudo docker build -t ${IMAGE_NAME} .
fi
