#!/bin/bash

source "${HOME}/.sdkman/bin/sdkman-init.sh"
source "${HOME}/.nvm/nvm.sh"

INIT_LOG=/root/init.log
EXPLORER_LOGS_FOLDER="/var/logs/explorer"
EXPLORER_ROOT_FOLDER="${HOME}/lumino-explorer/lumino-explorer-api"
EXPLORER_WEB_ROOT_FOLDER="${HOME}/lumino-explorer/lumino-explorer-web"
EXPLORER_POM_FILE="${EXPLORER_ROOT_FOLDER}/pom.xml"
EXPLORER_CREATE_DB_FILE=/root/createDB.js
EXPLORER_DELETE_DB_FILE=/root/deleteDB.js


if [ "${EXPLORER_API_URL}}" == "" ]; then
    EXPLORER_API_URL="http://localhost:8080/api/v1/"
fi

if [ "${RSK_ENDPOINT}" == "" ]; then
    RSK_ENDPOINT="http://rsk-node:4444"
fi

if [ "${EXPLORER_PORT}" == "" ]; then
    EXPLORER_PORT=8080
fi

if [ "${TOKEN_NETWORK_REGISTRY}" == "" ]; then
    TOKEN_NETWORK_REGISTRY=0xed8c9163F888Bc2f9C4F299325003DA5fC8676DD
fi

if [ "${MONGO_DB_HOST}" == "" ]; then
    MONGO_DB_HOST="mongo-db"
fi

echo "Starting Explorer:" >> ${INIT_LOG}
echo "EXPLORER_API_URL=${EXPLORER_API_URL}" >> ${INIT_LOG}
echo "RSK_ENDPOINT=${RSK_ENDPOINT}" >> ${INIT_LOG}
echo "EXPLORER_PORT=${EXPLORER_PORT}" >> ${INIT_LOG}
echo "TOKEN_NETWORK_REGISTRY=${TOKEN_NETWORK_REGISTRY}" >> ${INIT_LOG}
echo "MONGO_DB_HOST=${MONGO_DB_HOST}" >> ${INIT_LOG}

echo "Building web"
cd "${EXPLORER_WEB_ROOT_FOLDER}" || exit
npm install && REACT_APP_API_URL="${EXPLORER_API_URL}" npm run build --production
mv "${EXPLORER_WEB_ROOT_FOLDER}/build" "/var/www/html/explorer"

# Init log folder
if [ ! -d "${EXPLORER_LOGS_FOLDER}" ]; then
    echo "Creating logs folder ${EXPLORER_LOGS_FOLDER}" >> ${INIT_LOG}
    mkdir -p "${EXPLORER_LOGS_FOLDER}"
fi

echo "Initializing explorer database" >> ${INIT_LOG}

# Init database
mongosh --host "${MONGO_DB_HOST}" < "${EXPLORER_DELETE_DB_FILE}" >> ${INIT_LOG}
mongosh --host "${MONGO_DB_HOST}" < "${EXPLORER_CREATE_DB_FILE}" >> ${INIT_LOG}

echo "Running explorer" >> ${INIT_LOG}
echo "mvn -f '${EXPLORER_POM_FILE}' spring-boot:run -Dspring-boot.run.jvmArguments='-Dserver.port=${EXPLORER_PORT} -Drsk.blockchain.endpoint=${RSK_ENDPOINT} -Dlumino.explorer.api.mongo.databasehost=${MONGO_DB_HOST} -Dlumino.contract.tokenNetworkRegistry=${TOKEN_NETWORK_REGISTRY}' > '${EXPLORER_LOGS_FOLDER}/server.log' 2>&1 &" >> ${INIT_LOG}

mvn -f "${EXPLORER_POM_FILE}" spring-boot:run -Dspring-boot.run.jvmArguments="-Dserver.port=${EXPLORER_PORT} -Drsk.blockchain.endpoint=${RSK_ENDPOINT} -Dlumino.explorer.api.mongo.databasehost=${MONGO_DB_HOST} -Dlumino.contract.tokenNetworkRegistry=${TOKEN_NETWORK_REGISTRY}" > "${EXPLORER_LOGS_FOLDER}/server.log" 2>&1 &
