#!/bin/bash

source "${HOME}/.sdkman/bin/sdkman-init.sh"

EXPLORER_LOGS_FOLDER="/var/logs/explorer"
EXPLORER_ROOT_FOLDER="${HOME}/lumino-explorer/lumino-explorer-api"
EXPLORER_POM_FILE="${EXPLORER_ROOT_FOLDER}/pom.xml"
EXPLORER_DATABASE_SETUP_FILE="${EXPLORER_ROOT_FOLDER}/src/main/resources/database/lumino-explorer-api-database-setup.js"

if [ "${RSK_ENDPOINT}" == "" ]; then
    RSK_ENDPOINT="http://rsk-node:4444"
fi

if [ "${EXPLORER_PORT}" == "" ]; then
    EXPLORER_PORT=8080
fi

if [ "${TOKEN_NETWORK_REGISTRY}" == "" ]; then
    TOKEN_NETWORK_REGISTRY=0xed8c9163F888Bc2f9C4F299325003DA5fC8676DD
fi

if [ "${MONGO_DB_USERNAME}" == "" ]; then
    MONGO_DB_USERNAME=root
fi

if [ "${MONGO_DB_PASSWORD}" == "" ]; then
    MONGO_DB_PASSWORD=infuy
fi

if [ "${MONGO_DB_HOST}" == "" ]; then
    MONGO_DB_HOST="mongo-db"
fi

# Init log folder
if [ ! -d "${EXPLORER_LOGS_FOLDER}" ]; then
    mkdir -p "${EXPLORER_LOGS_FOLDER}"
fi

# Init database
mongosh --host "${MONGO_DB_HOST}" -u "${MONGO_DB_USERNAME}" -p "${MONGO_DB_PASSWORD}" < "${EXPLORER_DATABASE_SETUP_FILE}"

mvn -f "${EXPLORER_POM_FILE}" spring-boot:run -Dspring-boot.run.jvmArguments=/
    "-Dserver.port=${EXPLORER_PORT}
     -Drsk.blockchain.endpoint=${RSK_ENDPOINT}
     -Dlumino.explorer.api.mongo.databasehost=${MONGO_DB_HOST}
     -Dlumino.contract.tokenNetworkRegistry=${TOKEN_NETWORK_REGISTRY}" > "${EXPLORER_LOGS_FOLDER}/server.log" 2>&1 &