version: "2.2"

services:
    mongo-db:
      image: "mongo"
      restart: "no"
      networks: ["regtest_network"]
      ports:
        - "27017"
        - "27018"
        - "27019"
    mysql-db:
      image: "mysql"
      command: --default-authentication-plugin=mysql_native_password
      restart:  "no"
      environment:
        MYSQL_ROOT_PASSWORD: infuy
      networks: ["regtest_network"]
      ports:
      - "3306"
      - "33060"
    rsk-node:
        image: "rsk-node-regtest-image:latest"
        restart: "no"
        networks: ["regtest_network"]
        volumes:
          - "./rsk-node/database:/var/lib/rsk/database/regtest"
        ports:
            - "4444"
            - "30305"

    lumino-explorer:
        #environment:
          #EXPLORER_API_URL: "http://explorer-api:8080/api/v1/" # this can use a dns name defined on hosts file to map to the final ip.
          #EXPLORER_PORT: 8080
          #RSK_ENDPOINT: "http://rsk-node:4444"
          #MONGO_DB_HOST: "mongo-db"
          #TOKEN_NETWORK_REGISTRY: 0xed8c9163F888Bc2f9C4F299325003DA5fC8676DD
        image: "lumino-explorer-regtest-image:latest"
        restart: "no"
        networks: ["regtest_network"]
        depends_on: ["mongo-db", "rsk-node"]
        ports:
            - "8080"
            - "80"
    rif-notifier:
      # Not used because startNotifier has all the parameters already set
      #environment:
        #NOTIFIER_PORT: 8080
        #RSK_ENDPOINT: "http://rsk-node:4444"
        #NOTIFIER_DB_URL: "jdbc:mysql://mysql-db:3306/rif_notifier" # Not compatible with replica option
        #NOTIFIER_DB_SCHEMA_NAME: "rif_notifier_1" # Not compatible with replica option
        #NOTIFIER_DB_USERNAME: root
        #NOTIFIER_DB_PASSWORD: infuy
        #TOKEN_NETWORK_REGISTRY: 0xed8c9163F888Bc2f9C4F299325003DA5fC8676DD
        #RNS_MULTICHAIN_CONTRACT: 0x73ec81da0C72DD112e06c09A6ec03B5544d26F05
      image: "rif-notifier-regtest-image:latest"
      restart: "no"
      networks: ["regtest_network"]
      depends_on: ["mysql-db", "rsk-node"]
      ports:
        - "8080"
      scale: 3

networks:
  regtest_network:
    external: true
