#!/bin/bash

echo "Are you sure you want to clean docker system? [y/N]?"

read SURE

if [ "${SURE}" != "y" ]; then
    echo "Canceling..."
    exit 0
fi

echo "Cleaning docker system..."
# Stopping and removing all containers
sudo docker stop $(sudo docker ps -a -q)
sudo docker rm $(sudo docker ps -a -q)

# Removing images
sudo docker system prune -a -f
echo "Done!"
