version: "2.2"

services:
    lumino-node:
        env_file:
          - "node1.env"
        build: "."
        restart: "no"
        network_mode: "host"
        volumes:
          - "${LUMINO_KEYSTORE_FOLDER}:/root/.ethereum/keystore"
          - "${RIF_CONFIG_KEY_FOLDER}:/root/.rif-comms"
          - "${RIF_CONFIG_FOLDER}:/root/rif-communications-pubsub-bootnode/config"