version: "2.0"

services:
    rsk-node:
        image: "rsk-node-image"
        container_name: "rsk-node-container"
        restart: "no"
        networks: ["local"]
        ports:
            - "4444"
            - "30305"

    lumino-explorer:
        environment:
          RSK_ENDPOINT: 'http://rsk-node:4444'
        image: "lumino-explorer-image"
        container_name: "lumino-explorer-container"
        restart: "no"
        networks: ["local"]
        depends_on: ["rsk-node"]
        ports:
            - "8080"

networks:
  local:
    external: true