#!/bin/bash

ROOT_FOLDER_NAME=${PWD##*/}

if ! command -v docker &> /dev/null
then
    echo "You need to install docker"
    exit 1
fi

if ! command -v docker-compose &> /dev/null
then
    echo "You need to install docker-compose"
    exit 1
fi

trap clean INT

function clean() {
    echo "Cleaning..."
    sudo docker-compose down
	rm -rf volumes/*
	echo "Done"
}

NETWORK=$(sudo docker network ls --filter name=lumino_network -q)
if [ "${NETWORK}" == "" ]; then
    echo "Creating network lumino_network"
    sudo docker network create lumino_network
fi

source .env

# TODO: tenemos que cargar el env dinamicamente, y arreglar el tema de los nombres de los contenedores

sudo docker-compose build
sudo docker-compose up -d
sudo docker exec -it "${ROOT_FOLDER_NAME}_lumino-node_1" "/root/lumino/startLumino"

clean

exit 0